### ISSUE TITLE
Improving color choice for text, background and buttons

### ISSUE THREAD

**Issue by scootergrisen** [openSUSE/linuxrc#144]
The text and background colors are not always good in linuxrc.
Sometimes i could not see the text. I guess because the text and the background have the same color.
And it can be hard to see which button is selected. Like if there is only two buttons.

**Comment by wfeldt** [comment]
linuxrc knows 3 different color schemes atm. Selectable via 'display=1' (2, 3) or the Settings->Display dialog (press ESC there to get the 'alternative' color scheme). The 3rd one (green/brown) is more of an Easter egg, though.

There's nothing against defining others, especially since there's now this boot menu option for selecting an installer color scheme. Just someone has to come up with some. :-)
